import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';

import { UsStates } from '@model';

/** NgModule version of Address Form generated by `ng generate @angular/material:address-form address2-form` */
Component({
  selector: 'app-address2-form',
  templateUrl: './address2-form.component.html',
  styleUrls: ['./address2-form.component.scss']
})
export class Address2FormComponent {
  addressForm = this.fb.group({
    company: null,
    firstName: [null, Validators.required],
    lastName: [null, Validators.required],
    address: [null, Validators.required],
    address2: null,
    city: [null, Validators.required],
    state: [null, Validators.required],
    postalCode: [null, Validators.compose([
      Validators.required, Validators.minLength(5), Validators.maxLength(5)])
    ],
    shipping: ['free', Validators.required]
  });

  hasUnitNumber = false;

  states = UsStates;

  constructor(private fb: FormBuilder) {}

  onSubmit(): void {
    alert('Thanks!');
  }
}
